In [2]:
import pandas as pd 
import numpy as np 
import warnings 
warnings. simplefilter ("ignore")

In [4]:
df = pd. read_csv("C:\\Users\\srmve\\Documents\\user_data.csv") 
df.head()

,user_id,submission_count,problem_solved,contribution,country,follower_count,last_online_time_seconds,max_rating,rating,rank,registration_time_seconds
0,user_3311,47,40,0,NaN,4,1504111645,348.337,330.849,intermediate,1466686436
1,user_3028,63,52,0,India,17,1498998165,405.677,339.450,intermediate,1441893325
2,user_2268,226,203,-8,Egypt,24,1505566052,307.339,284.404,beginner,1454267603
3,user_480,611,490,1,Ukraine,94,1505257499,525.803,471.330,advanced,1350720417
4,user_650,504,479,12,Russia,4,1496613433,548.739,486.525,advanced,1395560498

In [5]:
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3571 entries, 0 to 3570
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   user_id                    3571 non-null   object
 1   submission_count           3571 non-null   int64
 2   problem_solved             3571 non-null   int64
 3   contribution               3571 non-null   int64
 4   country                    2418 non-null   object
 5   follower_count             3571 non-null   int64
 6   last_online_time_seconds   3571 non-null   int64
 7   max_rating                 3571 non-null   float64
 8   rating                     3571 non-null   float64
 9   rank                       3571 non-null   object
 10  registration_time_seconds  3571 non-null   int64
dtypes: float64(2), int64(6), object(3)
memory usage: 307.0+ KB

In [6]:
df. describe ()

,submission_count,problem_solved,contribution,follower_count,last_online_time_seconds,max_rating,rating,registration_time_seconds
count,3571.000000,3571.000000,3571.000000,3571.000000,3.571000e+03,3571.000000,3571.000000,3.571000e+03
mean,299.481098,267.894427,4.102492,46.690563,1.502680e+09,390.374392,350.165578,1.434961e+09
std,366.102887,344.139688,16.552256,211.494638,5.114850e+06,92.428788,106.592503,4.750758e+07
min,1.000000,0.000000,-64.000000,0.000000,1.484237e+09,303.899000,0.000000,1.264761e+09
25%,66.500000,53.000000,0.000000,4.000000,1.502691e+09,317.661000,279.243000,1.416323e+09
50%,169.000000,146.000000,0.000000,13.000000,1.505054e+09,355.791000,329.702000,1.449085e+09
75%,390.000000,349.000000,0.000000,40.000000,1.505551e+09,444.954000,413.417500,1.470379e+09
max,4570.000000,4476.000000,171.000000,10575.000000,1.505595e+09,983.085000,911.124000,1.484236e+09

In [7]:
df. isnull (). sum ()

user_id                         0
submission_count                0
problem_solved                  0
contribution                    0
country                      1153
follower_count                  0
last_online_time_seconds        0
max_rating                      0
rating                          0
rank                            0
registration_time_seconds       0
dtype: int64

In [8]:
from sklearn. preprocessing import LabelEncoder 
label_encoder = LabelEncoder () 
categorical_columns = ['country', 'rank'] 
df[categorical_columns] = df[categorical_columns].apply(label_encoder.fit_transform) 
df[categorical_columns]

      country  rank
0          79     3
1          31     3
2          21     1
3          73     0
4          57     0
...       ...   ...
3566        5     1
3567       79     1
3568       79     1
3569       79     3
3570       62     1

[3571 rows x 2 columns]

In [9]:
from sklearn. impute import SimpleImputer 
numeric_columns = ['country'] 
df[numeric_columns] = SimpleImputer(strategy='mean'). fit_transform(df[numeric_columns]) 
df[numeric_columns]

      country
0        79.0
1        31.0
2        21.0
3        73.0
4        57.0
...       ...
3566      5.0
3567     79.0
3568     79.0
3569     79.0
3570     62.0

[3571 rows x 1 columns]

In [10]:
df = df. drop ('user_id', axis =1) 
df. head ()

,submission_count,problem_solved,contribution,country,follower_count,last_online_time_seconds,max_rating,rating,rank,registration_time_seconds
0,47,40,0,79.0,4,1504111645,348.337,330.849,3,1466686436
1,63,52,0,31.0,17,1498998165,405.677,339.450,3,1441893325
2,226,203,-8,21.0,24,1505566052,307.339,284.404,1,1454267603
3,611,490,1,73.0,94,1505257499,525.803,471.330,0,1350720417
4,504,479,12,57.0,4,1496613433,548.739,486.525,0,1395560498

In [11]:
x = df. iloc [:,  :-1] 
x

,submission_count,problem_solved,contribution,country,follower_count,last_online_time_seconds,max_rating,rating,rank
0,47,40,0,79.0,4,1504111645,348.337,330.849,3
1,63,52,0,31.0,17,1498998165,405.677,339.450,3
2,226,203,-8,21.0,24,1505566052,307.339,284.404,1
3,611,490,1,73.0,94,1505257499,525.803,471.330,0
4,504,479,12,57.0,4,1496613433,548.739,486.525,0
...,...,...,...,...,...,...,...,...,...
3566,161,120,0,5.0,42,1505409069,306.193,246.560,1
3567,41,30,0,79.0,0,1504026868,331.135,218.463,1
3568,58,51,0,79.0,0,1505552744,330.275,262.901,1
3569,148,137,0,79.0,2,1496606504,409.977,345.757,3
3570,163,115,6,62.0,40,1502074467,392.775,288.704,1

In [12]:
y = df. iloc[:,  -1] 
y

0       1466686436
1       1441893325
2       1454267603
3       1350720417
4       1395560498
           ...
3566    1455055521
3567    1465142933
3568    1480086231
3569    1480262887
3570    1455975499
Name: registration_time_seconds, Length: 3571, dtype: int64

In [13]:
from sklearn. model_selection import train_test_split 
x_train, x_test, y_train, y_test=train_test_split (x, y, random_state=0)

In [14]:
from sklearn. ensemble import RandomForestRegressor 
model = RandomForestRegressor (n_estimators=100, random_state=42)

In [15]:
model.fit (x_train, y_train)

RandomForestRegressor(random_state=42)

In [16]:
y_pred = model. predict(x_test) 
y_pred

array([1.45455496e+09, 1.43392280e+09, 1.39042627e+09, 1.45241261e+09,
       1.45483615e+09, 1.42245957e+09, 1.46665441e+09, 1.40576063e+09,
       1.45182356e+09, 1.40803296e+09, 1.44347665e+09, 1.45527652e+09,
       1.45833179e+09, 1.41039747e+09, 1.40353994e+09, 1.43335683e+09,
       1.45930505e+09, 1.48396266e+09, 1.45175827e+09, 1.46663339e+09,
       1.45883224e+09, 1.39686707e+09, 1.37510170e+09, 1.45583003e+09,
       1.43567271e+09, 1.46697796e+09, 1.42782285e+09, 1.35167334e+09,
       1.45055875e+09, 1.45104392e+09, 1.47095946e+09, 1.43119661e+09,
       1.39180426e+09, 1.45824164e+09, 1.44051569e+09, 1.46181146e+09,
       1.43774071e+09, 1.41057693e+09, 1.41982014e+09, 1.41032514e+09,
       1.46102952e+09, 1.44531362e+09, 1.44408272e+09, 1.43312909e+09,
       1.44923526e+09, 1.45480931e+09, 1.46493558e+09, 1.38739107e+09,
       1.46522130e+09, 1.34720321e+09, 1.44306016e+09, 1.43258882e+09,
       1.45973789e+09, 1.44872871e+09, 1.41464911e+09, 1.43173064e+09,
       1.47030693e+09, 1.41554286e+09, 1.45349140e+09, 1.45890839e+09,
       1.37963785e+09, 1.39024897e+09, 1.46494454e+09, 1.39503257e+09,
       1.36973396e+09, 1.46910568e+09, 1.45365958e+09, 1.44598027e+09,
       1.45992361e+09, 1.39585475e+09, 1.36215790e+09, 1.44300388e+09,
       1.42957886e+09, 1.45861093e+09, 1.39488787e+09, 1.46234938e+09,
       1.42973465e+09, 1.39827533e+09, 1.42849457e+09, 1.40362502e+09,
       1.38430622e+09, 1.43231123e+09, 1.40130961e+09, 1.45066829e+09,
       1.41483941e+09, 1.44737396e+09, 1.37554480e+09, 1.40647814e+09,
       1.46431379e+09, 1.42297468e+09, 1.43807063e+09, 1.44079918e+09,
       1.42702444e+09, 1.46730581e+09, 1.41186844e+09, 1.44883324e+09,
       1.42776033e+09, 1.44911426e+09, 1.43723603e+09, 1.32336254e+09,
       1.42560790e+09, 1.47257838e+09, 1.46554379e+09, 1.44402171e+09,
       1.40077617e+09, 1.43746710e+09, 1.45207778e+09, 1.40332898e+09,
       1.46649596e+09, 1.39066182e+09, 1.45865937e+09, 1.44302456e+09,
       1.42683161e+09, 1.37944160e+09, 1.47552847e+09, 1.44794144e+09,
       1.36675439e+09, 1.44863875e+09, 1.45514361e+09, 1.45873512e+09,
       1.45477335e+09, 1.31990620e+09, 1.37752611e+09, 1.42605709e+09,
       1.44625732e+09, 1.41895722e+09, 1.38962137e+09, 1.41479959e+09,
       1.39101344e+09, 1.42274663e+09, 1.43243601e+09, 1.44118935e+09,
       1.31765116e+09, 1.44108567e+09, 1.46367149e+09, 1.44450598e+09,
       1.43084039e+09, 1.46106598e+09, 1.39697190e+09, 1.44418962e+09,
       1.46888421e+09, 1.43629901e+09, 1.42461707e+09, 1.45388903e+09,
       1.45435616e+09, 1.46726282e+09, 1.46545126e+09, 1.43839501e+09,
       1.46300649e+09, 1.38321688e+09, 1.45347088e+09, 1.44385357e+09,
       1.39207136e+09, 1.46933402e+09, 1.46085386e+09, 1.39614957e+09,
       1.43804694e+09, 1.44620178e+09, 1.43788073e+09, 1.45121521e+09,
       1.45008962e+09, 1.46139074e+09, 1.33482027e+09, 1.45985586e+09,
       1.46259963e+09, 1.45270201e+09, 1.43041453e+09, 1.44412209e+09,
       1.45547809e+09, 1.39251891e+09, 1.43837006e+09, 1.37875814e+09,
       1.44869655e+09, 1.45968886e+09, 1.39231741e+09, 1.45171014e+09,
       1.42501414e+09, 1.44958428e+09, 1.41672130e+09, 1.44874428e+09,
       1.41773420e+09, 1.45087331e+09, 1.45788484e+09, 1.43696486e+09,
       1.44307264e+09, 1.46937539e+09, 1.46031408e+09, 1.46200173e+09,
       1.45252452e+09, 1.45817371e+09, 1.41776207e+09, 1.46764479e+09,
       1.45365250e+09, 1.39873363e+09, 1.47055847e+09, 1.45934781e+09,
       1.45853024e+09, 1.38832087e+09, 1.48144555e+09, 1.40629573e+09,
       1.46024401e+09, 1.44497591e+09, 1.41131686e+09, 1.41623002e+09,
       1.42524235e+09, 1.44220730e+09, 1.43769122e+09, 1.37634955e+09,
       1.45944847e+09, 1.44533995e+09, 1.34957202e+09, 1.45557173e+09,
       1.40655821e+09, 1.45522057e+09, 1.40107062e+09, 1.46857011e+09,
       1.42493132e+09, 1.39472055e+09, 1.43240838e+09, 1.44774159e+09,
       1.43095824e+09, 1.41941761e+09, 1.40339560e+09, 1.46348377e+09,
       1.38021133e+09, 1.43560849e+09, 1.29570811e+09, 1.39820397e+09,
       1.44994669e+09, 1.47810858e+09, 1.38233622e+09, 1.43523316e+09,
       1.45105824e+09, 1.39049461e+09, 1.45731982e+09, 1.45252682e+09,
       1.48012376e+09, 1.41872910e+09, 1.46781429e+09, 1.47397494e+09,
       1.43505272e+09, 1.44017673e+09, 1.42755596e+09, 1.34701968e+09,
       1.46355460e+09, 1.40715805e+09, 1.45470773e+09, 1.42153967e+09,
       1.43069626e+09, 1.45638243e+09, 1.39732207e+09, 1.35233963e+09,
       1.38908734e+09, 1.45648634e+09, 1.38923953e+09, 1.46687316e+09,
       1.44872517e+09, 1.41700888e+09, 1.40160981e+09, 1.43559091e+09,
       1.39774011e+09, 1.46350556e+09, 1.45011449e+09, 1.42214206e+09,
       1.40151921e+09, 1.45183607e+09, 1.46677135e+09, 1.45016912e+09,
       1.46991062e+09, 1.41104288e+09, 1.46277724e+09, 1.43242897e+09,
       1.46344766e+09, 1.46085047e+09, 1.40618823e+09, 1.44275295e+09,
       1.45936030e+09, 1.43775114e+09, 1.42650278e+09, 1.43177325e+09,
       1.44916614e+09, 1.42818308e+09, 1.45245200e+09, 1.46402822e+09,
       1.45786691e+09, 1.39631435e+09, 1.44129896e+09, 1.45648613e+09,
       1.44875038e+09, 1.46182039e+09, 1.37465347e+09, 1.42280401e+09,
       1.46732392e+09, 1.44360839e+09, 1.46448850e+09, 1.45869694e+09,
       1.37252826e+09, 1.45724550e+09, 1.45544565e+09, 1.46271146e+09,
       1.43079972e+09, 1.42197533e+09, 1.40510849e+09, 1.41782392e+09,
       1.44405358e+09, 1.46231381e+09, 1.43561329e+09, 1.43872899e+09,
       1.46087498e+09, 1.44864790e+09, 1.32510758e+09, 1.45436533e+09,
       1.44947485e+09, 1.45799019e+09, 1.45962535e+09, 1.33962079e+09,
       1.45891046e+09, 1.44730660e+09, 1.45912500e+09, 1.44420006e+09,
       1.43452274e+09, 1.44727787e+09, 1.45518699e+09, 1.38056347e+09,
       1.37269726e+09, 1.42463827e+09, 1.43288719e+09, 1.38450459e+09,
       1.44778893e+09, 1.46006284e+09, 1.46609470e+09, 1.47297535e+09,
       1.44624622e+09, 1.42170593e+09, 1.46571457e+09, 1.43920355e+09,
       1.41847295e+09, 1.48225256e+09, 1.46440083e+09, 1.45639195e+09,
       1.46121505e+09, 1.46503641e+09, 1.46057891e+09, 1.45441153e+09,
       1.44462870e+09, 1.38448017e+09, 1.46476583e+09, 1.45259018e+09,
       1.42375850e+09, 1.46238364e+09, 1.44983636e+09, 1.43331273e+09,
       1.43823396e+09, 1.45434359e+09, 1.44782967e+09, 1.44132193e+09,
       1.44890608e+09, 1.46239548e+09, 1.46198385e+09, 1.44446574e+09,
       1.35476549e+09, 1.43897540e+09, 1.44500476e+09, 1.44593080e+09,
       1.38865145e+09, 1.43600986e+09, 1.37150805e+09, 1.44743183e+09,
       1.44335674e+09, 1.34367609e+09, 1.46966781e+09, 1.45836052e+09,
       1.43802598e+09, 1.42190893e+09, 1.43520779e+09, 1.45763074e+09,
       1.46016704e+09, 1.45995512e+09, 1.45351326e+09, 1.43830742e+09,
       1.43867940e+09, 1.47002604e+09, 1.46703755e+09, 1.37289629e+09,
       1.36874294e+09, 1.41416533e+09, 1.46723859e+09, 1.40068208e+09,
       1.43135467e+09, 1.46814032e+09, 1.43343177e+09, 1.45035078e+09,
       1.44814998e+09, 1.37884848e+09, 1.45196695e+09, 1.43089692e+09,
       1.42661104e+09, 1.45538811e+09, 1.46887431e+09, 1.45234171e+09,
       1.42708542e+09, 1.45689930e+09, 1.41981964e+09, 1.44018822e+09,
       1.33775310e+09, 1.47107944e+09, 1.44955214e+09, 1.46378352e+09,
       1.41094691e+09, 1.45935693e+09, 1.46685914e+09, 1.46474530e+09,
       1.45334208e+09, 1.43004831e+09, 1.44316529e+09, 1.42847427e+09,
       1.34187913e+09, 1.43206477e+09, 1.44672316e+09, 1.44052053e+09,
       1.45397645e+09, 1.46273455e+09, 1.45644990e+09, 1.42081111e+09,
       1.43659783e+09, 1.46411619e+09, 1.42669518e+09, 1.46156149e+09,
       1.46513379e+09, 1.45925534e+09, 1.40973681e+09, 1.43603615e+09,
       1.46687227e+09, 1.46624640e+09, 1.42837627e+09, 1.44562275e+09,
       1.44831582e+09, 1.45716997e+09, 1.46043349e+09, 1.44911117e+09,
       1.47033016e+09, 1.46603375e+09, 1.44793271e+09, 1.46602806e+09,
       1.43771750e+09, 1.44611041e+09, 1.45550897e+09, 1.45335513e+09,
       1.43315230e+09, 1.48394636e+09, 1.46659506e+09, 1.41487168e+09,
       1.45186397e+09, 1.42047214e+09, 1.41960386e+09, 1.41119499e+09,
       1.45621566e+09, 1.42495974e+09, 1.46457749e+09, 1.45164061e+09,
       1.42737405e+09, 1.38954814e+09, 1.42548487e+09, 1.39275255e+09,
       1.43197413e+09, 1.41030998e+09, 1.42907122e+09, 1.45876249e+09,
       1.45119592e+09, 1.45834855e+09, 1.41895224e+09, 1.47942816e+09,
       1.44188320e+09, 1.40046370e+09, 1.31173321e+09, 1.42818058e+09,
       1.43181881e+09, 1.41137518e+09, 1.40160389e+09, 1.46593505e+09,
       1.45773069e+09, 1.44898753e+09, 1.44907842e+09, 1.46084982e+09,
       1.43322258e+09, 1.43477107e+09, 1.44527878e+09, 1.45002682e+09,
       1.41825536e+09, 1.45166248e+09, 1.44582669e+09, 1.45952034e+09,
       1.40550443e+09, 1.39786471e+09, 1.46436033e+09, 1.46889367e+09,
       1.44991397e+09, 1.41604312e+09, 1.41639064e+09, 1.45212322e+09,
       1.46265658e+09, 1.45746228e+09, 1.44640255e+09, 1.45789187e+09,
       1.44129877e+09, 1.44511545e+09, 1.43076215e+09, 1.43080067e+09,
       1.41771023e+09, 1.45733283e+09, 1.42655746e+09, 1.47817783e+09,
       1.43663893e+09, 1.46046685e+09, 1.45862497e+09, 1.46450300e+09,
       1.43461923e+09, 1.41296164e+09, 1.45898931e+09, 1.43428477e+09,
       1.46169734e+09, 1.46701698e+09, 1.39112738e+09, 1.39504657e+09,
       1.41851051e+09, 1.45454658e+09, 1.44839349e+09, 1.45086515e+09,
       1.45872760e+09, 1.44643863e+09, 1.44782952e+09, 1.45997825e+09,
       1.35781525e+09, 1.44854905e+09, 1.37158445e+09, 1.46007064e+09,
       1.41422313e+09, 1.40466146e+09, 1.41724013e+09, 1.43645538e+09,
       1.46231706e+09, 1.45887482e+09, 1.43460568e+09, 1.37398042e+09,
       1.43955630e+09, 1.46784912e+09, 1.44455714e+09, 1.45400954e+09,
       1.45778282e+09, 1.42966410e+09, 1.45190794e+09, 1.45278856e+09,
       1.41509965e+09, 1.43823507e+09, 1.44278339e+09, 1.43397330e+09,
       1.45359170e+09, 1.45337423e+09, 1.44864559e+09, 1.42153995e+09,
       1.45207247e+09, 1.42408069e+09, 1.46014225e+09, 1.44517694e+09,
       1.44798795e+09, 1.43521488e+09, 1.45716732e+09, 1.38980133e+09,
       1.29875396e+09, 1.44368112e+09, 1.41391670e+09, 1.44946029e+09,
       1.42990556e+09, 1.39538610e+09, 1.46664287e+09, 1.47354338e+09,
       1.42608896e+09, 1.43913121e+09, 1.46064884e+09, 1.45462181e+09,
       1.42664041e+09, 1.43032496e+09, 1.44118393e+09, 1.37644540e+09,
       1.45241148e+09, 1.47885409e+09, 1.33161424e+09, 1.36879929e+09,
       1.41809644e+09, 1.43453365e+09, 1.43918837e+09, 1.43767727e+09,
       1.46069996e+09, 1.45543729e+09, 1.44838671e+09, 1.45457958e+09,
       1.44640859e+09, 1.43125015e+09, 1.45327403e+09, 1.46054176e+09,
       1.39052196e+09, 1.42801138e+09, 1.33082234e+09, 1.48170628e+09,
       1.35216138e+09, 1.38695370e+09, 1.44048790e+09, 1.44093196e+09,
       1.40703026e+09, 1.44168790e+09, 1.44610274e+09, 1.40595661e+09,
       1.44316571e+09, 1.41398890e+09, 1.45467135e+09, 1.45697666e+09,
       1.34093886e+09, 1.45320014e+09, 1.46104904e+09, 1.43680112e+09,
       1.45924611e+09, 1.45313882e+09, 1.45242795e+09, 1.39910787e+09,
       1.46103192e+09, 1.44109632e+09, 1.46814857e+09, 1.41679485e+09,
       1.45099737e+09, 1.43323261e+09, 1.43615733e+09, 1.45251298e+09,
       1.41337803e+09, 1.45514041e+09, 1.45744934e+09, 1.40207159e+09,
       1.46122711e+09, 1.47526806e+09, 1.45554381e+09, 1.44983026e+09,
       1.44459006e+09, 1.41257817e+09, 1.45100447e+09, 1.43026752e+09,
       1.40763337e+09, 1.46052089e+09, 1.47856113e+09, 1.44158747e+09,
       1.43946817e+09, 1.42046760e+09, 1.35497996e+09, 1.45691441e+09,
       1.44818706e+09, 1.46774937e+09, 1.44798124e+09, 1.38274381e+09,
       1.44134554e+09, 1.44630445e+09, 1.35170413e+09, 1.43395022e+09,
       1.38276887e+09, 1.45162014e+09, 1.44697686e+09, 1.45870315e+09,
       1.44515532e+09, 1.46209569e+09, 1.39366020e+09, 1.42791812e+09,
       1.39074785e+09, 1.43840266e+09, 1.41460445e+09, 1.46310078e+09,
       1.45495240e+09, 1.41410013e+09, 1.41329735e+09, 1.45133517e+09,
       1.47229307e+09, 1.45631799e+09, 1.47564821e+09, 1.45283727e+09,
       1.44435446e+09, 1.40273882e+09, 1.43444587e+09, 1.35975799e+09,
       1.42722002e+09, 1.46689394e+09, 1.45152939e+09, 1.44550276e+09,
       1.43801083e+09, 1.46205820e+09, 1.43213472e+09, 1.44800417e+09,
       1.38321105e+09, 1.44724796e+09, 1.45822405e+09, 1.46013055e+09,
       1.43271105e+09, 1.46567664e+09, 1.43674387e+09, 1.45683741e+09,
       1.31874571e+09, 1.43153281e+09, 1.44017525e+09, 1.44551727e+09,
       1.41104845e+09, 1.40882234e+09, 1.43187579e+09, 1.46834120e+09,
       1.45552544e+09, 1.46782030e+09, 1.44372943e+09, 1.46186939e+09,
       1.45774465e+09, 1.42659613e+09, 1.40710518e+09, 1.45177340e+09,
       1.45949554e+09, 1.42692828e+09, 1.46971290e+09, 1.41442592e+09,
       1.45873934e+09, 1.46497715e+09, 1.42463305e+09, 1.45247538e+09,
       1.45481164e+09, 1.44355537e+09, 1.42344295e+09, 1.43145160e+09,
       1.45786374e+09, 1.45238509e+09, 1.37107123e+09, 1.43575148e+09,
       1.33257962e+09, 1.45938768e+09, 1.45646750e+09, 1.46319367e+09,
       1.40988268e+09, 1.48274153e+09, 1.40356011e+09, 1.47565982e+09,
       1.45624194e+09, 1.44888850e+09, 1.46627873e+09, 1.38422517e+09,
       1.35131243e+09, 1.44884653e+09, 1.45601849e+09, 1.46494260e+09,
       1.43087012e+09, 1.43630450e+09, 1.43974229e+09, 1.42396799e+09,
       1.44503626e+09, 1.46862500e+09, 1.44226660e+09, 1.41504286e+09,
       1.40842402e+09, 1.47276592e+09, 1.44671089e+09, 1.44522489e+09,
       1.46705793e+09, 1.44988628e+09, 1.47094171e+09, 1.46059667e+09,
       1.43345361e+09, 1.43788897e+09, 1.44560763e+09, 1.44506269e+09,
       1.43500861e+09, 1.43285409e+09, 1.44604121e+09, 1.35945629e+09,
       1.42418923e+09, 1.46149443e+09, 1.45154079e+09, 1.43618082e+09,
       1.45751202e+09, 1.43544517e+09, 1.43872401e+09, 1.44747344e+09,
       1.45856642e+09, 1.44648537e+09, 1.41665008e+09, 1.40398479e+09,
       1.39857756e+09, 1.46576925e+09, 1.44854661e+09, 1.43342040e+09,
       1.39032583e+09, 1.43976921e+09, 1.42832054e+09, 1.32914704e+09,
       1.36033098e+09, 1.44592092e+09, 1.45044963e+09, 1.46912818e+09,
       1.43090878e+09, 1.44869895e+09, 1.37729703e+09, 1.42681892e+09,
       1.43068121e+09, 1.32730964e+09, 1.37850828e+09, 1.43985302e+09,
       1.43622807e+09, 1.43230457e+09, 1.39723436e+09, 1.44398074e+09,
       1.42422047e+09, 1.44783565e+09, 1.42742666e+09, 1.37467374e+09,
       1.45226108e+09, 1.41732752e+09, 1.44109092e+09, 1.45913725e+09,
       1.39813949e+09, 1.44538741e+09, 1.43227484e+09, 1.44802258e+09,
       1.44394069e+09, 1.45640726e+09, 1.43792069e+09, 1.42496511e+09,
       1.45603273e+09, 1.38911290e+09, 1.38116070e+09, 1.38769755e+09,
       1.43921075e+09, 1.42849862e+09, 1.44459193e+09, 1.44980711e+09,
       1.45041081e+09, 1.40625255e+09, 1.42427263e+09, 1.37408391e+09,
       1.43452255e+09, 1.42781689e+09, 1.44990112e+09, 1.45907146e+09,
       1.41108342e+09, 1.43758387e+09, 1.48228083e+09, 1.42631935e+09,
       1.35975465e+09, 1.45986502e+09, 1.42734139e+09, 1.45186003e+09,
       1.47956607e+09, 1.46568954e+09, 1.42556200e+09, 1.41875586e+09,
       1.44296370e+09, 1.45159455e+09, 1.46449976e+09, 1.46289276e+09,
       1.46288786e+09, 1.44642912e+09, 1.46565554e+09, 1.45405087e+09,
       1.36318141e+09, 1.38339118e+09, 1.45015183e+09, 1.38902591e+09,
       1.44561047e+09, 1.37198952e+09, 1.42540653e+09, 1.42679242e+09,
       1.33123535e+09, 1.42697124e+09, 1.45735531e+09, 1.43013529e+09,
       1.42509245e+09, 1.43596984e+09, 1.38689660e+09, 1.47142025e+09,
       1.43395822e+09, 1.45684635e+09, 1.42288934e+09, 1.43007908e+09,
       1.45352541e+09, 1.38979533e+09, 1.41027651e+09, 1.39602271e+09,
       1.42039650e+09, 1.43567671e+09, 1.45998340e+09, 1.46253477e+09,
       1.36404119e+09, 1.40199870e+09, 1.46185540e+09, 1.43398266e+09,
       1.45531434e+09])

In [17]:
from sklearn. metrics import mean_squared_error 
mse = mean_squared_error (y_test, y_pred) 
print (f'Mean Squared Error: {mse}')

Mean Squared Error: 1269410250004051.2

In [18]:
new_data = [161, 120, 0, 5.0, 42, 1505409069, 306.193, 246.560,1] 
predictions = model. predict([new_data]) 
print(predictions)

[1.45716732e+09]